// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var MapboxGl = require("mapbox-gl");
var Caml_external_polyfill = require("bs-platform/lib/js/caml_external_polyfill.js");

var map = new MapboxGl.Map();

var mapWithOpt = Caml_external_polyfill.resolve("Map")({
      container: "app-hash-in-dom"
    });

console.log(map, mapWithOpt);

exports.map = map;
exports.mapWithOpt = mapWithOpt;
/* map Not a pure module */
